#!/usr/bin/env python2

import sys

from consai2_gui.visualizer import Visualizer
from rqt_gui.main import Main

plugin = 'consai2_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
